# Generated by Django 4.2.30 on 2026-10-02 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0001_initial'),
        ('matches', '0001_initial'),
        ('venues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('total_scanned', models.PositiveIntegerField(default=0, verbose_name='total scannés')),
                ('total_valid', models.PositiveIntegerField(default=0, verbose_name='valides')),
                ('total_rejected', models.PositiveIntegerField(default=0, verbose_name='refusés')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_sessions', to=settings.AUTH_USER_MODEL)),
                ('gate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_sessions', to='venues.gate')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_sessions', to='matches.match')),
            ],
            options={
                'verbose_name': 'session de scan',
                'verbose_name_plural': 'sessions de scan',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('qr_token_received', models.CharField(blank=True, max_length=200, verbose_name='token QR reçu')),
                ('result', models.CharField(choices=[('valid', 'Valide ✅'), ('already_used', 'Déjà utilisé ❌'), ('invalid_qr', 'QR invalide ⛔'), ('wrong_match', 'Mauvais match ⚠️'), ('ticket_cancelled', 'Billet annulé 🚫'), ('not_found', 'Billet introuvable 🔍')], max_length=20, verbose_name='résultat')),
                ('scanned_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('client_uuid', models.UUIDField(blank=True, db_index=True, help_text='UUID généré côté client pour la sync offline.', null=True, verbose_name='identifiant client')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='scanner.scansession')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_logs', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'log de scan',
                'verbose_name_plural': 'logs de scan',
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.AddIndex(
            model_name='scansession',
            index=models.Index(fields=['match', 'agent'], name='scanner_sca_match_i_958a86_idx'),
        ),
        migrations.AddIndex(
            model_name='scanlog',
            index=models.Index(fields=['session', 'result'], name='scanner_sca_session_d45db0_idx'),
        ),
    ]
