# Generated by Django 4.2.30 on 2026-10-02 15:28

import apps.orders.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identifiant public sécurisé (utilisé dans les URLs).', unique=True, verbose_name='identifiant public')),
                ('order_number', models.CharField(default=apps.orders.models.generate_order_number, max_length=20, unique=True, verbose_name='numéro de commande')),
                ('guest_email', models.EmailField(blank=True, max_length=254, verbose_name='email invité')),
                ('guest_phone', models.CharField(blank=True, max_length=20, verbose_name='téléphone invité')),
                ('guest_first_name', models.CharField(blank=True, max_length=100, verbose_name='prénom invité')),
                ('guest_last_name', models.CharField(blank=True, max_length=100, verbose_name='nom invité')),
                ('subtotal', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='sous-total')),
                ('fees', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='frais de service')),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='total payé')),
                ('status', models.CharField(choices=[('pending', 'En attente de paiement'), ('paid', 'Payée'), ('failed', 'Échouée'), ('cancelled', 'Annulée'), ('refunded', 'Remboursée')], default='pending', max_length=20, verbose_name='statut')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='payé le')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='annulé le')),
                ('access_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name="jeton d'accès")),
                ('buyer', models.ForeignKey(blank=True, help_text='Null si achat sans compte (guest).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='matches.match')),
            ],
            options={
                'verbose_name': 'commande',
                'verbose_name_plural': 'commandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantité')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='prix unitaire')),
                ('subtotal', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='sous-total')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='tickets.ticketcategory')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
            options={
                'verbose_name': 'ligne de commande',
                'verbose_name_plural': 'lignes de commande',
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='orders_orde_status_25e057_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['buyer', 'status'], name='orders_orde_buyer_i_4389c9_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='orders_orde_order_n_f3ada5_idx'),
        ),
    ]
