# Generated by Django 4.2.30 on 2026-10-02 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identifiant public sécurisé (utilisé dans les URLs).', unique=True, verbose_name='identifiant public')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('first_name', models.CharField(max_length=100, verbose_name='prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='nom')),
                ('phone', models.CharField(blank=True, help_text='Format international : +225XXXXXXXXXX', max_length=20, verbose_name='téléphone')),
                ('role', models.CharField(choices=[('supporter', 'Supporter'), ('team_staff', 'Personnel équipe'), ('org_staff', 'Personnel organisation'), ('scanner', 'Agent scanner'), ('admin', 'Administrateur plateforme')], default='supporter', max_length=20, verbose_name='rôle')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('is_staff', models.BooleanField(default=False, verbose_name='accès admin')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='inscrit le')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'utilisateur',
                'verbose_name_plural': 'utilisateurs',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='SupporterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('favorite_team_id', models.PositiveBigIntegerField(blank=True, help_text="ID de l'équipe favorite (ajouté plus tard).", null=True)),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='ville')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='date de naissance')),
                ('accepts_marketing', models.BooleanField(default=False, verbose_name='accepte les promos')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supporter_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profil supporter',
                'verbose_name_plural': 'profils supporters',
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('team_id', models.PositiveBigIntegerField(blank=True, help_text="ID de l'équipe (si role=team_staff).", null=True)),
                ('organization_id', models.PositiveBigIntegerField(blank=True, help_text="ID de l'organisation (si role=org_staff).", null=True)),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='poste')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profil personnel',
                'verbose_name_plural': 'profils personnel',
            },
        ),
    ]
