# Generated by Django 4.2.30 on 2026-10-02 15:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identifiant public sécurisé (utilisé dans les URLs).', unique=True, verbose_name='identifiant public')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='nom')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='slug')),
                ('type', models.CharField(choices=[('championship', 'Championnat'), ('cup', 'Coupe'), ('friendly', 'Match amical')], default='championship', max_length=20, verbose_name='type')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='competitions/logos/%Y/%m/', verbose_name='logo')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'compétition',
                'verbose_name_plural': 'compétitions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identifiant public sécurisé (utilisé dans les URLs).', unique=True, verbose_name='identifiant public')),
                ('name', models.CharField(help_text='Ex : 2026-2027, Édition 2026...', max_length=50, verbose_name='nom')),
                ('start_date', models.DateField(verbose_name='date de début')),
                ('end_date', models.DateField(verbose_name='date de fin')),
                ('is_current', models.BooleanField(default=False, help_text='Cocher pour la saison actuellement active.', verbose_name='saison en cours')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='competitions.competition')),
            ],
            options={
                'verbose_name': 'saison',
                'verbose_name_plural': 'saisons',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='MatchDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('number', models.PositiveIntegerField(verbose_name='numéro')),
                ('name', models.CharField(blank=True, help_text="Optionnel. Si vide, 'Journée N' est utilisé.", max_length=100, verbose_name='nom')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='date de fin')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_days', to='competitions.season')),
            ],
            options={
                'verbose_name': 'journée',
                'verbose_name_plural': 'journées',
                'ordering': ['season', 'number'],
            },
        ),
        migrations.AddConstraint(
            model_name='season',
            constraint=models.UniqueConstraint(fields=('competition', 'name'), name='unique_season_per_competition'),
        ),
        migrations.AddConstraint(
            model_name='matchday',
            constraint=models.UniqueConstraint(fields=('season', 'number'), name='unique_matchday_per_season'),
        ),
    ]
