# Generated by Django 4.2.30 on 2026-10-07 14:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identifiant public sécurisé (utilisé dans les URLs).', unique=True, verbose_name='identifiant public')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='nom')),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True, verbose_name='slug')),
                ('kind', models.CharField(choices=[('team', "Sport d'équipe"), ('combat', 'Sport de combat')], default='team', max_length=20, verbose_name='type')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('rules', models.JSONField(blank=True, default=dict, verbose_name='règles / configuration')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name="ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'verbose_name': 'sport',
                'verbose_name_plural': 'sports',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
