# Generated by Django 4.2.30 on 2026-10-02 15:30

import apps.payouts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identifiant public sécurisé (utilisé dans les URLs).', unique=True, verbose_name='identifiant public')),
                ('reference', models.CharField(default=apps.payouts.models.generate_payout_reference, max_length=20, unique=True, verbose_name='référence')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='montant demandé')),
                ('fee', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='frais')),
                ('amount_net', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='montant net reversé')),
                ('payout_method', models.CharField(choices=[('wave', 'Wave'), ('orange', 'Orange Money'), ('mtn', 'MTN MoMo'), ('moov', 'Moov Money')], max_length=20, verbose_name='méthode')),
                ('payout_phone', models.CharField(max_length=20, verbose_name='numéro Mobile Money')),
                ('payout_name', models.CharField(max_length=200, verbose_name='nom bénéficiaire')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Réussi'), ('failed', 'Échoué'), ('cancelled', 'Annulé'), ('rejected', 'Rejeté')], default='pending', max_length=20, verbose_name='statut')),
                ('admin_note', models.TextField(blank=True, verbose_name='note admin')),
                ('provider', models.CharField(default='paydunya', max_length=30, verbose_name='provider')),
                ('provider_token', models.CharField(blank=True, max_length=200, verbose_name='token provider')),
                ('provider_transaction_id', models.CharField(blank=True, max_length=200, verbose_name='transaction provider')),
                ('provider_status', models.CharField(blank=True, max_length=50, verbose_name='statut provider')),
                ('retry_count', models.PositiveIntegerField(default=0, verbose_name='retries')),
                ('last_error', models.TextField(blank=True, verbose_name='dernière erreur')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='traité le')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='complété le')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'demande de reversement',
                'verbose_name_plural': 'demandes de reversement',
                'ordering': ['-created_at'],
            },
        ),
    ]
