# Generated by Django 4.2.30 on 2026-10-02 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payouts', '0001_initial'),
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutrequest',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_requests', to='wallet.teamwallet'),
        ),
        migrations.AddIndex(
            model_name='payoutrequest',
            index=models.Index(fields=['wallet', 'status'], name='payouts_pay_wallet__cef53d_idx'),
        ),
        migrations.AddIndex(
            model_name='payoutrequest',
            index=models.Index(fields=['status'], name='payouts_pay_status_e8ed6b_idx'),
        ),
    ]
