# Generated by Django 4.2.30 on 2026-10-02 15:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identifiant public sécurisé (utilisé dans les URLs).', unique=True, verbose_name='identifiant public')),
                ('provider', models.CharField(choices=[('wave', 'Wave'), ('orange', 'Orange Money'), ('mtn', 'MTN MoMo'), ('moov', 'Moov Money'), ('card', 'Carte bancaire')], max_length=20, verbose_name='moyen de paiement')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='montant')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('success', 'Réussi'), ('failed', 'Échoué'), ('cancelled', 'Annulé'), ('refunded', 'Remboursé')], default='pending', max_length=20, verbose_name='statut')),
                ('provider_reference', models.CharField(blank=True, max_length=200, verbose_name='référence provider')),
                ('provider_token', models.CharField(blank=True, max_length=200, verbose_name='token provider')),
                ('provider_status', models.CharField(blank=True, max_length=50, verbose_name='statut provider')),
                ('last_error', models.TextField(blank=True, verbose_name='dernière erreur')),
                ('initiated_at', models.DateTimeField(blank=True, null=True, verbose_name='initié le')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='complété le')),
                ('last_webhook_token', models.CharField(blank=True, help_text='Évite de traiter deux fois le même webhook.', max_length=200, verbose_name='dernier token webhook')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
            ],
            options={
                'verbose_name': 'paiement',
                'verbose_name_plural': 'paiements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='payments_pa_status_343680_idx'), models.Index(fields=['order', 'status'], name='payments_pa_order_i_a76289_idx')],
            },
        ),
    ]
