# Generated by Django 4.2.30 on 2026-10-02 15:16

import apps.tickets.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venues', '0001_initial'),
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('name', models.CharField(help_text='Ex : Populaire, Tribune, VIP, Loge...', max_length=100, verbose_name='nom')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='prix (FCFA)')),
                ('total_quantity', models.PositiveIntegerField(help_text='Nombre de places disponibles dans cette catégorie.', verbose_name='quantité totale')),
                ('quantity_sold', models.PositiveIntegerField(default=0, editable=False, verbose_name='vendues')),
                ('max_per_order', models.PositiveIntegerField(default=10, verbose_name='max par commande')),
                ('block_label', models.CharField(blank=True, help_text='Ex : Bloc 12, Tribune Sud...', max_length=50, verbose_name='bloc / tribune')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('gate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_categories', to='venues.gate', verbose_name="porte d'accès")),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_categories', to='matches.match')),
            ],
            options={
                'verbose_name': 'catégorie de billets',
                'verbose_name_plural': 'catégories de billets',
                'ordering': ['match', 'order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identifiant public sécurisé (utilisé dans les URLs).', unique=True, verbose_name='identifiant public')),
                ('ticket_number', models.CharField(default=apps.tickets.models.generate_ticket_number, max_length=20, unique=True, verbose_name='numéro de billet')),
                ('order_id', models.PositiveBigIntegerField(blank=True, db_index=True, help_text='ID de la commande (ajouté quand orders existera).', null=True)),
                ('gate_label', models.CharField(blank=True, max_length=50, verbose_name='porte')),
                ('block_label', models.CharField(blank=True, max_length=50, verbose_name='bloc')),
                ('row_label', models.CharField(blank=True, max_length=20, verbose_name='rangée')),
                ('seat_label', models.CharField(blank=True, max_length=20, verbose_name='siège')),
                ('holder_name', models.CharField(blank=True, max_length=200, verbose_name='nom du porteur')),
                ('holder_email', models.EmailField(blank=True, max_length=254, verbose_name='email du porteur')),
                ('holder_phone', models.CharField(blank=True, max_length=20, verbose_name='téléphone du porteur')),
                ('qr_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='jeton QR')),
                ('status', models.CharField(choices=[('valid', 'Valide'), ('used', 'Utilisé'), ('cancelled', 'Annulé'), ('refunded', 'Remboursé')], default='valid', max_length=20, verbose_name='statut')),
                ('first_scanned_at', models.DateTimeField(blank=True, null=True, verbose_name='premier scan')),
                ('scanned_count', models.PositiveIntegerField(default=0, verbose_name='nombre de scans')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.ticketcategory')),
            ],
            options={
                'verbose_name': 'billet',
                'verbose_name_plural': 'billets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='ticketcategory',
            constraint=models.UniqueConstraint(fields=('match', 'name'), name='unique_category_per_match'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['ticket_number'], name='tickets_tic_ticket__bf3905_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', 'category'], name='tickets_tic_status_8eba12_idx'),
        ),
    ]
