# Generated by Django 4.2.30 on 2026-10-05 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='qr_code_data',
            field=models.CharField(blank=True, help_text='Payload encodé dans le QR (STADIUM:<qr_token>).', max_length=200, verbose_name='données QR'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='tickets/qr/%Y/%m/', verbose_name='image QR'),
        ),
    ]
