# Generated by Django 4.2.30 on 2026-10-02 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('balance_available', models.DecimalField(decimal_places=0, default=0, help_text='Montant disponible pour reversement.', max_digits=14, verbose_name='solde disponible')),
                ('balance_pending', models.DecimalField(decimal_places=0, default=0, help_text='Montant réservé pour un reversement en cours.', max_digits=14, verbose_name='solde en attente')),
                ('balance_withdrawn', models.DecimalField(decimal_places=0, default=0, help_text='Total cumulé des reversements effectués.', max_digits=14, verbose_name='total reversé')),
                ('preferred_payout_method', models.CharField(choices=[('wave', 'Wave'), ('orange', 'Orange Money'), ('mtn', 'MTN MoMo'), ('moov', 'Moov Money')], default='wave', max_length=20, verbose_name='méthode de reversement préférée')),
                ('payout_phone', models.CharField(blank=True, max_length=20, verbose_name='numéro Mobile Money')),
                ('payout_name', models.CharField(blank=True, max_length=200, verbose_name='nom du bénéficiaire')),
                ('is_frozen', models.BooleanField(default=False, help_text='Wallet gelé : aucun reversement accepté.', verbose_name='gelé')),
                ('frozen_reason', models.TextField(blank=True, verbose_name='raison du gel')),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='teams.team')),
            ],
            options={
                'verbose_name': 'portefeuille équipe',
                'verbose_name_plural': 'portefeuilles équipes',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('type', models.CharField(choices=[('credit', 'Crédit (vente)'), ('debit', 'Débit (reversement)'), ('adjustment', 'Ajustement manuel'), ('refund', 'Remboursement')], max_length=20, verbose_name='type')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='montant')),
                ('balance_after', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='solde après')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='description')),
                ('reference', models.CharField(blank=True, max_length=200, verbose_name='référence')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.teamwallet')),
            ],
            options={
                'verbose_name': 'transaction wallet',
                'verbose_name_plural': 'transactions wallet',
                'ordering': ['-created_at'],
            },
        ),
    ]
