# Generated by Django 4.2.30 on 2026-10-02 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('action', models.CharField(choices=[('login', 'Connexion'), ('logout', 'Déconnexion'), ('order_created', 'Commande créée'), ('order_paid', 'Commande payée'), ('order_cancelled', 'Commande annulée'), ('order_refunded', 'Commande remboursée'), ('payment_initiated', 'Paiement initié'), ('payment_success', 'Paiement réussi'), ('payment_failed', 'Paiement échoué'), ('ticket_created', 'Billet généré'), ('ticket_scanned', 'Billet scanné'), ('payout_requested', 'Reversement demandé'), ('payout_completed', 'Reversement effectué'), ('payout_failed', 'Reversement échoué'), ('wallet_frozen', 'Wallet gelé'), ('wallet_unfrozen', 'Wallet dégelé'), ('other', 'Autre')], max_length=30, verbose_name='action')),
                ('description', models.TextField(verbose_name='description')),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='modèle')),
                ('object_id', models.CharField(blank=True, max_length=100, verbose_name='ID objet')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='métadonnées')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='adresse IP')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='user-agent')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "entrée d'audit",
                'verbose_name_plural': "journal d'audit",
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='audit_audit_action_766c6d_idx'), models.Index(fields=['user', 'created_at'], name='audit_audit_user_id_a3c2bc_idx')],
            },
        ),
    ]
