# Generated by Django 4.2.30 on 2026-10-02 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identifiant public sécurisé (utilisé dans les URLs).', unique=True, verbose_name='identifiant public')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='nom complet')),
                ('short_name', models.CharField(help_text='Ex : ASEC, Africa Sports, SOA...', max_length=50, verbose_name='nom court')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='slug')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='ville')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='teams/logos/%Y/%m/', verbose_name='logo')),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='année de fondation')),
                ('president_name', models.CharField(blank=True, max_length=200, verbose_name='président')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('stadium', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_teams', to='venues.venue', verbose_name='stade domicile')),
            ],
            options={
                'verbose_name': 'équipe',
                'verbose_name_plural': 'équipes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TeamStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('role', models.CharField(choices=[('manager', 'Responsable / Président'), ('coach', 'Entraîneur'), ('medical', 'Médical'), ('communication', 'Communication'), ('other', 'Autre')], default='other', max_length=20, verbose_name='rôle')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='teams.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'membre du staff',
                'verbose_name_plural': 'membres du staff',
            },
        ),
        migrations.AddConstraint(
            model_name='teamstaff',
            constraint=models.UniqueConstraint(fields=('user', 'team', 'role'), name='unique_user_team_role'),
        ),
    ]
