# Generated by Django 4.2.30 on 2026-10-07 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
        ('teams', '0002_team_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='sport',
            field=models.ForeignKey(blank=True, help_text='Sport pratiqué (null pour compat historique).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='sports.sport'),
        ),
    ]
