# Generated by Django 4.2.30 on 2026-10-02 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchStatsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('date', models.DateField(verbose_name='date')),
                ('tickets_sold', models.PositiveIntegerField(default=0, verbose_name='billets vendus')),
                ('revenue', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='revenus (FCFA)')),
                ('tickets_scanned', models.PositiveIntegerField(default=0, verbose_name='billets scannés')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats_snapshots', to='matches.match')),
            ],
            options={
                'verbose_name': 'statistiques match (snapshot)',
                'verbose_name_plural': 'statistiques match (snapshots)',
                'ordering': ['-date'],
            },
        ),
        migrations.AddConstraint(
            model_name='matchstatssnapshot',
            constraint=models.UniqueConstraint(fields=('match', 'date'), name='unique_snapshot_per_match_per_day'),
        ),
    ]
