# Generated by Django 4.2.30 on 2026-10-02 14:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identifiant public sécurisé (utilisé dans les URLs).', unique=True, verbose_name='identifiant public')),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('address', models.TextField(blank=True, verbose_name='adresse')),
                ('city', models.CharField(max_length=100, verbose_name='ville')),
                ('country', models.CharField(default="Côte d'Ivoire", max_length=100, verbose_name='pays')),
                ('capacity', models.PositiveIntegerField(default=0, help_text='0 = non renseigné.', verbose_name='capacité totale')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('image', models.ImageField(blank=True, null=True, upload_to='venues/%Y/%m/', verbose_name='image')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'verbose_name': 'stade',
                'verbose_name_plural': 'stades',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Gate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('name', models.CharField(help_text='Ex : Porte A, Porte Principale...', max_length=50, verbose_name='nom')),
                ('code', models.CharField(help_text="Code court utilisé pour l'attribution (ex : A, B, C).", max_length=10, verbose_name='code')),
                ('zone', models.CharField(blank=True, help_text='Ex : Virage Nord, Tribune Sud...', max_length=100, verbose_name='zone')),
                ('capacity_per_hour', models.PositiveIntegerField(default=0, help_text='0 = non renseigné.', verbose_name='débit horaire')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gates', to='venues.venue')),
            ],
            options={
                'verbose_name': "porte d'entrée",
                'verbose_name_plural': "portes d'entrée",
                'ordering': ['venue', 'code'],
            },
        ),
        migrations.AddConstraint(
            model_name='gate',
            constraint=models.UniqueConstraint(fields=('venue', 'code'), name='unique_gate_per_venue'),
        ),
    ]
