# Generated by Django 4.2.30 on 2026-10-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_venue_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='zone_template',
            field=models.JSONField(blank=True, default=list, help_text='Template des zones pour ce lieu. Format : [{"name": "Virage Nord", "capacity": 5000, "price_base": 1000}, ...]. Copié dans les catégories de billets à la création d\'un match.', verbose_name='zones par défaut'),
        ),
    ]
