# Generated by Django 4.2.30 on 2026-10-05 12:33

import apps.organizations.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identifiant public sécurisé (utilisé dans les URLs).', unique=True, verbose_name='identifiant public')),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('slug', models.SlugField(default=apps.organizations.models.generate_slug, editable=False, max_length=20, unique=True, verbose_name='slug')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email de contact')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='téléphone')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='adresse')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='ville')),
                ('logo_url', models.URLField(blank=True, verbose_name='URL du logo')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('owner', models.ForeignKey(help_text="Utilisateur responsable principal de l'organisation.", on_delete=django.db.models.deletion.PROTECT, related_name='owned_organizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'organisation',
                'verbose_name_plural': 'organisations',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='organizatio_slug_048085_idx'), models.Index(fields=['owner', 'is_active'], name='organizatio_owner_i_01d693_idx')],
            },
        ),
    ]
