# Generated by Django 4.2.30 on 2026-10-02 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Notification push')], max_length=20, verbose_name='canal')),
                ('kind', models.CharField(choices=[('order_confirmed', 'Commande confirmée'), ('tickets_ready', 'Billets disponibles'), ('match_reminder', 'Rappel de match'), ('password_reset', 'Réinitialisation mot de passe'), ('payout_requested', 'Reversement demandé'), ('payout_completed', 'Reversement effectué'), ('other', 'Autre')], default='other', max_length=30, verbose_name='type')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('sent', 'Envoyée'), ('failed', 'Échouée')], default='pending', max_length=20, verbose_name='statut')),
                ('recipient_email', models.EmailField(blank=True, max_length=254, verbose_name='email destinataire')),
                ('recipient_phone', models.CharField(blank=True, max_length=20, verbose_name='téléphone destinataire')),
                ('subject', models.CharField(blank=True, max_length=300, verbose_name='sujet')),
                ('body_preview', models.CharField(blank=True, max_length=500, verbose_name='aperçu du message')),
                ('order_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('payout_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='envoyé le')),
                ('error_message', models.TextField(blank=True, verbose_name='erreur')),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='notificatio_status_68c9bc_idx'), models.Index(fields=['kind'], name='notificatio_kind_b7435e_idx')],
            },
        ),
    ]
