# Generated by Django 4.2.30 on 2026-10-02 15:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        ('competitions', '0001_initial'),
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identifiant public sécurisé (utilisé dans les URLs).', unique=True, verbose_name='identifiant public')),
                ('kickoff_at', models.DateTimeField(help_text='Date et heure du début du match.', verbose_name="coup d'envoi")),
                ('sale_start_at', models.DateTimeField(blank=True, null=True, verbose_name='ouverture des ventes')),
                ('sale_end_at', models.DateTimeField(blank=True, null=True, verbose_name='fermeture des ventes')),
                ('away_quota_percent', models.PositiveIntegerField(default=10, help_text="Pourcentage de places réservées à l'équipe visiteuse.", verbose_name='quota équipe visiteuse (%)')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('configuring', 'En configuration'), ('on_sale', 'En vente'), ('sold_out', 'Complet'), ('closed', 'Vente fermée'), ('cancelled', 'Annulé'), ('played', 'Joué')], default='draft', max_length=20, verbose_name='statut')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='matches/posters/%Y/%m/', verbose_name='affiche')),
                ('tv_channel', models.CharField(blank=True, max_length=100, verbose_name='chaîne TV')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='away_matches', to='teams.team', verbose_name='équipe visiteuse')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='competitions.competition')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_matches', to='teams.team', verbose_name='équipe recevante')),
                ('match_day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='competitions.matchday')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='competitions.season')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='venues.venue')),
            ],
            options={
                'verbose_name': 'match',
                'verbose_name_plural': 'matchs',
                'ordering': ['-kickoff_at'],
                'indexes': [models.Index(fields=['status', 'kickoff_at'], name='matches_mat_status_951bb1_idx'), models.Index(fields=['home_team', 'kickoff_at'], name='matches_mat_home_te_be5760_idx')],
            },
        ),
    ]
