# Generated by Django 4.2.30 on 2026-10-05 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organisation propriétaire (null = donnée historique).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='organizations.organization'),
        ),
    ]
